# Generated by Django 5.2.1 on 2025-05-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pendiente'), ('E', 'Entregado')], default='P', max_length=1),
        ),
    ]
